---
framework: jest
preRun:
  command:
    - yarn install

preMerge:
  env:
    NODE_ENV: test
  pattern:
    - "src/__tests__/*-test.js"

postMerge:
  env:
    NODE_ENV: test
  pattern:
    - "src/__tests__/*-test.js"

postRun:
  command:
    - yarn --version
version: 1.0
configFile: "./jest.config.js"
